---
- include_vars: "default.yaml"
  tags:
    - pin
    - patch

- include_vars: "{{ ansible_distribution | lower }}_{{ ansible_distribution_major_version }}.yaml"
  when: ansible_distribution == "RedHat" or ansible_distribution == "Ubuntu" or ansible_distribution == "Amazon"
  tags:
    - pin

- include: pin-kernel.yaml
  tags:
    - pin

- include: patch.yaml
  tags:
    - patch